quarkus.application.name=notification-service
quarkus.http.port=8080

%prod.kafka.bootstrap.servers=localhost:9092
mp.messaging.incoming.notifications.connector=smallrye-kafka
mp.messaging.incoming.notifications.topic=notificationTopic
mp.messaging.incoming.notifications.group.id=notificationId
mp.messaging.incoming.notifications.key.deserializer=org.apache.kafka.common.serialization.StringDeserializer
mp.messaging.incoming.notifications.value.deserializer=com.ibatulanand.notificationservice.OrderPlacedEventDeserializer
mp.messaging.incoming.notifications.auto.offset.reset=earliest
mp.messaging.incoming.notifications.fail-on-deserialization-failure=false
mp.messaging.incoming.notifications.failure-strategy=ignore

quarkus.otel.exporter.otlp.endpoint=http://localhost:4317
quarkus.otel.traces.sampler=always_on
quarkus.jackson.fail-on-unknown-properties=false

quarkus.log.console.format=%d{HH:mm:ss} %-5p [notification-service,%X{traceId},%X{spanId}] (%t) %s%e%n

quarkus.container-image.group=ibatulanandjp
quarkus.container-image.name=notification-service
quarkus.container-image.tag=latest
