quarkus.application.name=api-gateway
quarkus.http.port=8181

quarkus.oidc.auth-server-url=http://localhost:8080/realms/spring-boot-microservices-realm
quarkus.oidc.application-type=service

quarkus.http.auth.permission.public.paths=/eureka,/eureka/*,/q/health,/q/health/*,/q/metrics
quarkus.http.auth.permission.public.policy=permit
quarkus.http.auth.permission.authenticated.paths=/*
quarkus.http.auth.permission.authenticated.policy=authenticated

quarkus.stork.product-service.service-discovery.type=consul
quarkus.stork.product-service.service-discovery.consul-host=${CONSUL_HOST:localhost}
quarkus.stork.product-service.service-discovery.consul-port=${CONSUL_PORT:8500}
quarkus.stork.product-service.load-balancer.type=round-robin
quarkus.stork.order-service.service-discovery.type=consul
quarkus.stork.order-service.service-discovery.consul-host=${CONSUL_HOST:localhost}
quarkus.stork.order-service.service-discovery.consul-port=${CONSUL_PORT:8500}
quarkus.stork.order-service.load-balancer.type=round-robin

gateway.consul-ui.url=${CONSUL_UI_URL:http://localhost:8500}

quarkus.otel.exporter.otlp.endpoint=${OTEL_EXPORTER_OTLP_ENDPOINT:http://localhost:4317}
quarkus.otel.traces.sampler=always_on
quarkus.log.console.format=%d{yyyy-MM-dd HH:mm:ss,SSS} %5p [api-gateway,%X{traceId},%X{spanId}] (%t) %s%e%n

quarkus.container-image.group=ibatulanandjp
quarkus.container-image.name=api-gateway
quarkus.container-image.tag=latest
