quarkus.http.port=8080

quarkus.datasource.db-kind=mysql
quarkus.datasource.jdbc.url=${QUARKUS_DATASOURCE_JDBC_URL:jdbc:mysql://localhost:3306/order_service?createDatabaseIfNotExist=true}
quarkus.datasource.username=${QUARKUS_DATASOURCE_USERNAME:root}
quarkus.datasource.password=${QUARKUS_DATASOURCE_PASSWORD:mysql}
quarkus.hibernate-orm.database.generation=update

quarkus.rest-client.inventory.uri=stork://inventory-service
quarkus.stork.inventory-service.service-discovery.type=consul
quarkus.stork.inventory-service.service-discovery.consul-host=${CONSUL_HOST:localhost}
quarkus.stork.inventory-service.service-discovery.consul-port=${CONSUL_PORT:8500}
quarkus.stork.inventory-service.load-balancer.type=round-robin

kafka.bootstrap.servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
mp.messaging.outgoing.notificationTopic.connector=smallrye-kafka
mp.messaging.outgoing.notificationTopic.topic=notificationTopic
mp.messaging.outgoing.notificationTopic.key.serializer=org.apache.kafka.common.serialization.StringSerializer
mp.messaging.outgoing.notificationTopic.value.serializer=io.quarkus.kafka.client.serialization.ObjectMapperSerializer

quarkus.otel.exporter.otlp.endpoint=${OTEL_EXPORTER_OTLP_ENDPOINT:http://localhost:4317}
quarkus.otel.traces.sampler=always_on

quarkus.log.console.format=%d{yyyy-MM-dd HH:mm:ss,SSS} %5p [order-service,%X{traceId},%X{spanId}] [%c{2.}] (%t) %s%e%n
quarkus.container-image.group=ibatulanandjp
quarkus.container-image.name=order-service