quarkus.http.port=8080
quarkus.mongodb.connection-string=mongodb://localhost:27017
quarkus.mongodb.database=product-service
quarkus.otel.exporter.otlp.endpoint=http://localhost:4317
quarkus.otel.traces.sampler=always_on
quarkus.container-image.group=ibatulanandjp
quarkus.container-image.name=product-service
quarkus.jackson.fail-on-unknown-properties=false
quarkus.log.console.format=%d{yyyy-MM-dd HH:mm:ss} %-5p [product-service,%X{traceId},%X{spanId}] (%t) %s%e%n
