quarkus.application.name=inventory-service
quarkus.http.port=8080

quarkus.datasource.db-kind=mysql
quarkus.datasource.username=root
quarkus.datasource.password=mysql
%prod.quarkus.datasource.jdbc.url=jdbc:mysql://localhost:3306/inventory_service

quarkus.hibernate-orm.database.generation=update

quarkus.otel.exporter.otlp.endpoint=http://localhost:4317
quarkus.otel.traces.sampler=always_on
quarkus.log.console.format=%d{HH:mm:ss} %-5p [inventory-service,%X{traceId},%X{spanId}] (%t) %s%e%n

quarkus.container-image.group=ibatulanandjp
quarkus.container-image.name=inventory-service
quarkus.jib.base-jvm-image=eclipse-temurin:17.0.4.1_1-jre

%test.inventory.seed.enabled=false
